### ISSUE TITLE
How to switch screen orientation for transaction activities?

### ISSUE THREAD

**Issue by cmcfatter** [AuthorizeNet/inperson-sdk-android#73]
Is there a way to change the orientation of the transaction activities for the Android In-Person SDK? Right now it forces portrait orientation when it displays the total charge and then after that it forces landscape orientation for the signature.

Any help with this would be appreciated.

**Comment by amimishr** [comment]
@cmcfatter currently we do not have this functionality. The orientation change from portrait to landscape for signature is due to the reason that it gives more ON_SCREEN space for signing.  

However there is a way you can skip the signature screen. If you are using the following "startQuickChipTransaction", then there is a flag "showSignature" you can pass-on. 

public static void startQuickChipTransaction(EMVTransaction emvTransaction, final QuickChipTransactionSessionListener quickChipTransactionSessionListener, Context context, boolean  showSignature, boolean isAuthOnlyTransaction)


However if you are skipping on screen signatures, you might be required to capture on-receipt signatures on paper.
